### ISSUE TITLE
Uploading an invalid add-on ZIP gives no response to the user

### ISSUE THREAD

**Issue by DemianWright** [McTwist/Blockland-Repository#29]
Laravel gives a validation error but nothing is displayed in the UI to tell the user about this.

**Comment by McTwist** [comment]
Would you like to add something to this bug, or can I mark it as fixed?

**Comment by DemianWright** [comment]
Well it still doesn't work. I uploaded a ZIP with a random name containing a PDF file and it worked just fine. Just complained that it didn't have a namecheck and that version 0.0 was wrong. I though the idea was to disallow uploading ZIP's that do not begin with one of the valid add-on type prefixes?

**Comment by DemianWright** [comment]
Additionally the problem still persists where after attempting to upload an invalid add-on (e.g. a brick add-on with no server.cs), it gives "Unknown internal error" for all valid file uploads until you refresh/reopen the popup.

**Comment by McTwist** [comment]
The "Unknown internal error" is due to a Dropzone bug. I currently does not know why this happens, but you should open a new issue for that one.

The lack of description might be a validation bug. I'm looking into it.

I tested uploading one without a type, and it declined it without letting me modify anything. Are you sure you got the newest pull?

**Comment by McTwist** [comment]
d39909fcee3de634117bb9bb295b433fdc52f23c should fix the description bug.

**Comment by McTwist** [comment]
The type bug is not a bug. The system behaves by allowing any type, as long as the name contain at least one underscore. It will, however, complain if known types does not contain valid files in it.

I'll mark this as fixed.
